tutorial done

diff --git a/node-js-buildpack/bin/build b/node-js-buildpack/bin/build
--- a/node-js-buildpack/bin/build
+++ b/node-js-buildpack/bin/build
@@ -1,9 +1,37 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -eo pipefail
 
-layers_dir="$1"
-env_dir="$2/env"
-plan_path="$3"
+echo "---> NodeJS Buildpack"
 
-exit 0
+# 1. CREATE THE LAYER DIRECTORY
+node_js_layer="${CNB_LAYERS_DIR}"/node-js
+mkdir -p "${node_js_layer}"
+
+# 2. DOWNLOAD node-js
+node_js_version="18.18.1"
+node_js_url=https://nodejs.org/dist/v${node_js_version}/node-v${node_js_version}-linux-x64.tar.xz
+cached_nodejs_version=$(cat "${CNB_LAYERS_DIR}/node-js.toml" 2> /dev/null | yj -t | jq -r .metadata.nodejs_version 2>/dev/null || echo 'NOT FOUND')
+if [[ "${node_js_url}" != *"${cached_nodejs_version}"* ]] ; then
+    echo "-----> Downloading and extracting NodeJS"
+    wget -q -O - "${node_js_url}" | tar -xJf - --strip-components 1 -C "${node_js_layer}"
+else
+    echo "-----> Reusing NodeJS"
+fi
+
+# 3. MAKE node-js AVAILABLE DURING LAUNCH and CACHE the LAYER
+cat > "${CNB_LAYERS_DIR}/node-js.toml" << EOL
+[types]
+cache = true
+launch = true
+[metadata]
+nodejs_version = "${node_js_version}"
+EOL
+
+# 4. SET DEFAULT START COMMAND
+cat > "${CNB_LAYERS_DIR}/launch.toml" << EOL
+[[processes]]
+type = "web"
+command = ["node", "app.js"]
+default = true
+EOL
